# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33be133a1b6e173031448ed6c1232f00d22d37083ed97a5ca81ddef2975fd6d6c58caffbbcd975bed8c710b4798e8f523c634e09c1d08627685bbc5e98238f89

test:
  secret_key_base: 9a89050050cc90d5e5cf34f34a0be4a95f9b5ef120a6e70b5a31cfe778a495319374d79eb66bc0b6e388ce8d7aa09997d2340d975cd23ae1aeec0fd8472e800a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
